image:
  file: .gitpod.Dockerfile

ports:
  - port: 6080

tasks:
  - init: |
      virtualenv -p $(which python3) pyenv
    command: |
      source pyenv/bin/activate
      pip install -r requirements.txt
      python server.py
